name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '25,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        mkdir -p data
        curl https://distribution-te-prod.prod.svc-test-trace.nhs.uk/distribution/risky-venues \
          | jq . > data/risky-venues.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push